# environment.yml
name: credit-risk
channels:
  - defaults
  - conda-forge
  - pytorch
  - nvidia
dependencies:
  # Base Python & utilities
  - python=3.10
  - pip
  - pip:
      # Core libraries
      - numpy==1.27.4
      - pandas==2.2.2
      - pyarrow==12.0.1
      - scikit-learn==1.3.2
      - lightgbm==4.0.0
      - fastapi==0.95.2
      - uvicorn[standard]==0.22.0
      - mlflow==2.5.1
      - shap==0.41.0
      - evidently==0.3.2
      - requests==2.31.0

  # PySpark (for scalable ETL)
  - pyspark==3.4.1

  # PyTorch & GPU support (CPU-only fallback works too)
  - pytorch==2.2.0
  - torchvision==0.17.0
  - torchaudio==2.2.0
  # PyTorch Geometric dependencies
  - pyg-lib==0.2.0.post1
  - torch-scatter==2.1.1
  - torch-sparse==0.6.20
  - torch-cluster==1.6.1
  - torch-spline-conv==1.2.1
  - torch-geometric==2.3.0

  # Optional blockchain for notarization
  - web3==6.5.0

  # Optional telemetry
  - opentelemetry-api==1.17.0
  - opentelemetry-sdk==1.17.0
  - opentelemetry-instrumentation-fastapi==0.39b0
